Repository mapbox/turf-swift, pull requests merged in 2020-11, with the labels that each got.

#120 Make CLLocationCoordinate2D members public on Linux
  Sources/Turf/CoreLocation.swift
Labels: bug, build

#121 v1.1.0
  README.md
  Sources/Turf/Info.plist
  Tests/TurfTests/Info.plist
  Turf.podspec
  Turf.xcodeproj/project.pbxproj
Labels: build

#122 Update README.md to mention Turf.js bearing
  README.md
Labels: documentation
