Repository mapbox/turf-swift, pull requests merged in 2021-09, with the labels that each got.

#152 Various bug fixes for LineString.simplify and Polygon.simplify
  Sources/Turf/Geometries/LineString.swift
  Sources/Turf/Geometries/Polygon.swift
  Sources/Turf/Simplifier.swift
  Tests/TurfTests/Fixture.swift
  Tests/TurfTests/Fixtures/simplify/in/argentina.geojson
  Tests/TurfTests/Fixtures/simplify/in/featurecollection.geojson
  Tests/TurfTests/Fixtures/simplify/in/fiji-hiQ.geojson
  Tests/TurfTests/Fixtures/simplify/in/issue-#1144.geojson
  Tests/TurfTests/Fixtures/simplify/in/linestring.geojson
  Tests/TurfTests/Fixtures/simplify/in/multipoint.geojson
  Tests/TurfTests/Fixtures/simplify/in/point.geojson
  Tests/TurfTests/Fixtures/simplify/in/poly-issue#555-5.geojson
  Tests/TurfTests/Fixtures/simplify/in/polygon.geojson
  Tests/TurfTests/Fixtures/simplify/in/simple-polygon.geojson
  Tests/TurfTests/Fixtures/simplify/out/argentina.geojson
  Tests/TurfTests/Fixtures/simplify/out/featurecollection.geojson
  Tests/TurfTests/Fixtures/simplify/out/fiji-hiQ.geojson
  Tests/TurfTests/Fixtures/simplify/out/issue-#1144.geojson
  Tests/TurfTests/Fixtures/simplify/out/linestring.geojson
  Tests/TurfTests/Fixtures/simplify/out/multipoint.geojson
  Tests/TurfTests/Fixtures/simplify/out/point.geojson
  Tests/TurfTests/Fixtures/simplify/out/poly-issue#555-5.geojson
  Tests/TurfTests/Fixtures/simplify/out/polygon.geojson
  Tests/TurfTests/Fixtures/simplify/out/simple-polygon.geojson
  Tests/TurfTests/LineStringTests.swift
  Tests/TurfTests/PolygonTests.swift
  Tests/TurfTests/TurfTests.swift
  Turf.xcodeproj/project.pbxproj
Labels: bug, refactor

#154 Compliant, codable, equatable GeoJSON
  Sources/Turf/BoundingBox.swift
  Sources/Turf/Codable.swift
  Sources/Turf/Feature.swift
  Sources/Turf/FeatureCollection.swift
  Sources/Turf/FeatureIdentifier.swift
  Sources/Turf/GeoJSON.swift
  Sources/Turf/Geometries/GeometryCollection.swift
  Sources/Turf/Geometries/LineString.swift
  Sources/Turf/Geometries/MultiLineString.swift
  Sources/Turf/Geometries/MultiPoint.swift
  Sources/Turf/Geometries/MultiPolygon.swift
  Sources/Turf/Geometries/Point.swift
  Sources/Turf/Geometries/Polygon.swift
  Sources/Turf/Geometry.swift
  Sources/Turf/JSON.swift
  Sources/Turf/Ring.swift
  Tests/TurfTests/FeatureCollectionTests.swift
  Tests/TurfTests/Fixtures/featurecollection.geojson
  Tests/TurfTests/Fixtures/simplify/in/featurecollection.geojson
  Tests/TurfTests/Fixtures/simplify/out/featurecollection.geojson
  Tests/TurfTests/GeoJSONTests.swift
  Tests/TurfTests/GeometryCollectionTests.swift
  Tests/TurfTests/JSONTests.swift
  Tests/TurfTests/LineStringTests.swift
  Tests/TurfTests/MultiLineStringTests.swift
  Tests/TurfTests/MultiPointTests.swift
  Tests/TurfTests/MultiPolygonTests.swift
  Tests/TurfTests/PointTests.swift
  Tests/TurfTests/PolygonTests.swift
  Tests/TurfTests/TurfTests.swift
  Turf.xcodeproj/project.pbxproj
Labels: bug, enhancement, refactor, backwards-incompatible

#157 v2.0.0-rc.2
  Sources/Turf/Info.plist
  Tests/TurfTests/Info.plist
  Turf.podspec
  Turf.xcodeproj/project.pbxproj
Labels: build
